pull_request_rules:
  - name: automatic merge for Dependabot devDependencies pull requests
    conditions:
      - author=renovate[bot]
      - title~=^chore\(deps\)
      - check-success=e2e (ubuntu-latest)
      - check-success=e2e (windows-latest)
      - check-success=build_and_test (16.x, ubuntu-latest)
      - check-success=build_and_test (16.x, windows-latest)
      - check-success=build_and_test (14.18.0, ubuntu-latest)
      - check-success=build_and_test (14.18.0, windows-latest)
    actions:
      merge:
        method: squash
      squash:
        commit_message: first-commit # this should be the dependabot commit, with a nice message
