pull_request_rules:
  - name: automatic merge for Dependabot devDependencies pull requests
    conditions:
      - author=dependabot
      - check-success=build_and_test (12.x, ubuntu-latest)
      - check-success=build_and_test (12.x, windows-latest)
      - check-success=build_and_test (14.x, ubuntu-latest)
      - check-success=build_and_test (14.x, windows-latest)
      - title~=^build\(deps-dev\)
    actions:
      merge:
        method: squash
      squash:
        commit_message: first-commit # this should be the dependabot commit, with a nice message
