packages:
  - 'packages/*'
  - 'e2e'
  - 'e2e/test/*'
minimumReleaseAge: 4320 # 3 days, see: https://pnpm.io/settings#minimumreleaseage
minimumReleaseAgeExclude:
  # Renovate security update: axios@1.13.5 || 1.15.0
  - axios@1.13.5 || 1.15.0
  # Renovate security update: @sveltejs/kit@2.52.2 || 2.53.3 || 2.57.1
  - "@sveltejs/kit@2.52.2 || 2.53.3 || 2.57.1"
  # Renovate security update: svelte@5.51.5 || 5.53.5 || 5.55.7
  - svelte@5.51.5 || 5.53.5 || 5.55.7
  # Renovate security update: ajv@8.18.0
  - ajv@8.18.0
  # Renovate security update: minimatch@10.2.4
  - minimatch@10.2.4
  # Try out TS 7.0.1-rc
  - typescript
  - '@typescript/typescript-linux-ppc64'
  - '@typescript/typescript-win32-x64'
  - '@typescript/typescript-linux-riscv64'
  - '@typescript/typescript-linux-arm64'
  - '@typescript/typescript-linux-s390x'
  - '@typescript/typescript-freebsd-arm64'
  - '@typescript/typescript-darwin-x64'
  - '@typescript/typescript-linux-x64'
  - '@typescript/typescript-aix-ppc64'
  - '@typescript/typescript-freebsd-x64'
  - '@typescript/typescript-netbsd-x64'
  - '@typescript/typescript-linux-mips64el'
  - '@typescript/typescript-win32-arm64'
  - '@typescript/typescript-netbsd-arm64'
  - '@typescript/typescript-openbsd-x64'
  - '@typescript/typescript-linux-loong64'
  - '@typescript/typescript-sunos-x64'
  - '@typescript/typescript-darwin-arm64'
  - '@typescript/typescript-openbsd-arm64'
  - '@typescript/typescript-linux-arm'