import NodeMutatorFactory from '../NodeMutatorFactory';
import ArrayLiteralMutator from './ArrayLiteralMutator';
import ArrayNewExpressionMutator from './ArrayNewExpressionMutator';
import BinaryExpressionMutator from './BinaryExpressionMutator';
import BlockMutator from './BlockMutator';
import BooleanSubstitutionMutator from './BooleanSubstitutionMutator';
import PrefixUnaryExpressionMutator from './PrefixUnaryExpressionMutator';
import PostfixUnaryExpressionMutator from './PostfixUnaryExpressionMutator';
import RemoveConditionalsMutator from './RemoveConditionalsMutator';
import WhileStatementMutator from './WhileStatementMutator';

const factory = NodeMutatorFactory.instance();
factory.register(ArrayLiteralMutator.name, ArrayLiteralMutator);
factory.register(ArrayNewExpressionMutator.name, ArrayNewExpressionMutator);
factory.register(BinaryExpressionMutator.name, BinaryExpressionMutator);
factory.register(BlockMutator.name, BlockMutator);
factory.register(BooleanSubstitutionMutator.name, BooleanSubstitutionMutator);
factory.register(PrefixUnaryExpressionMutator.name, PrefixUnaryExpressionMutator);
factory.register(PostfixUnaryExpressionMutator.name, PostfixUnaryExpressionMutator);
factory.register(RemoveConditionalsMutator.name, RemoveConditionalsMutator);
factory.register(WhileStatementMutator.name, WhileStatementMutator);