import NodeMutatorFactory from '../NodeMutatorFactory';
import ArrayLiteralMutator from './ArrayLiteralMutator';
import ArrayNewExpressionMutator from './ArrayNewExpressionMutator';
import BinaryExpressionMutator from './BinaryExpressionMutator';
import BlockMutator from './BlockMutator';
import BooleanSubstitutionMutator from './BooleanSubstitutionMutator';
import RemoveConditionalsMutator from './RemoveConditionalsMutator';
import UnaryOperatorMutator from './UnaryOperatorMutator';
import UpdateOperatorMutator from './UpdateOperatorMutator';
import WhileStatementMutator from './WhileStatementMutator';

const factory = NodeMutatorFactory.instance();
factory.register(ArrayLiteralMutator.name, ArrayLiteralMutator);
factory.register(ArrayNewExpressionMutator.name, ArrayNewExpressionMutator);
factory.register(BinaryExpressionMutator.name, BinaryExpressionMutator);
factory.register(BlockMutator.name, BlockMutator);
factory.register(BooleanSubstitutionMutator.name, BooleanSubstitutionMutator);
factory.register(RemoveConditionalsMutator.name, RemoveConditionalsMutator);
factory.register(UnaryOperatorMutator.name, UnaryOperatorMutator);
factory.register(UpdateOperatorMutator.name, UpdateOperatorMutator);
factory.register(WhileStatementMutator.name, WhileStatementMutator);