export const checkerPool = 'checkerPool';
export const checkerFactory = 'checkerFactory';
export const checkerConcurrencyTokens = 'checkerConcurrencyTokens';
export const cliOptions = 'cliOptions';
export const configReader = 'configReader';
export const configOptionsApplier = 'configOptionsApplier'; // TODO: Remove if unused post mutation switching
export const inputFiles = 'inputFiles';
export const dryRunResult = 'dryRunResult';
export const transpiledFiles = 'transpiledFiles'; // TODO: Remove if unused post mutation switching
export const files = 'files';
export const mutants = 'mutants';
export const mutantsWithTestCoverage = 'mutantsWithTestCoverage';
export const mutantTranspileScheduler = 'mutantTranspileScheduler'; // TODO: Remove if unused post mutation switching
export const temporaryDirectory = 'temporaryDirectory';
export const timer = 'timer';
export const timeOverheadMS = 'timeOverheadMS';
export const loggingContext = 'loggingContext';
export const mutationTestReportHelper = 'mutationTestReportHelper';
export const transpiler = 'transpiler';
export const sandbox = 'sandbox';
export const sandboxWorkingDirectory = 'sandboxWorkingDirectory'; // TODO: Remove if unused post mutation switching
export const concurrencyTokenProvider = 'concurrencyTokenProvider';
export const testRunnerFactory = 'testRunnerFactory';
export const testRunnerPool = 'testRunnerPool';
export const testRunnerConcurrencyTokens = 'testRunnerConcurrencyTokens';
export const reporter = 'reporter';
export const pluginKind = 'pluginKind';
export const pluginDescriptors = 'pluginDescriptors';
export const pluginCreatorReporter = 'pluginCreatorReporter';
export const pluginCreatorConfigEditor = 'pluginCreatorConfigEditor';
export const pluginCreatorChecker = 'pluginCreatorChecker';
export const pluginCreatorOptionsEditor = 'pluginCreatorOptionsEditor';
export const pluginCreatorTranspiler = 'pluginCreatorTranspiler';
export const pluginCreatorTestRunner = 'pluginCreatorTestRunner';
export const pluginCreatorMutator = 'pluginCreatorMutator';
export const pluginCreatorTestFramework = 'pluginCreatorTestFramework';
export const validationSchema = 'validationSchema';
export const optionsValidator = 'optionsValidator';
