language: node_js
node_js:
  - "node"
  - "7"
  - "6"
  - "4"
before_install: 
  - npm install -g grunt-cli
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install: npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
