name: Publish

on:
  push:
    tags:
      - '**' # Fine when using locked versioning mode with lerna, as only one tag is pushed to git.

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup
        with:
          install-chromium: false
      - name: Build
        run: pnpm run build
      - name: Release
        run: pnpm exec lerna publish from-git --yes --pre-dist-tag next
